include:
  - project: 'resengit/gitlab/pipeline-helpers'
    ref: main
    file: '/pipelines/docker-image.yaml'
  - project: 'resengit/gitlab/pipeline-helpers'
    ref: 'main'
    file: '/pipelines/helm-chart.yaml'

variables:
  PH_DOCKER_KANIKO_IMAGE: gcr.io/kaniko-project/executor:v1.20.1-debug
  PH_HELM_CHART_FOLDER: chart

documentation_website_trigger:
  trigger:
    project: 'icos/documentation'
    branch: 'develop'
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - docs/**/*